# -*- coding: utf-8 -*-
"""sentence similarity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8Ao9XVorym3HGhkWg5Sl0D8XB-O7sR3
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util
#Load the model
model = SentenceTransformer('all-MiniLM-L6-v2')
#Take input from user
text1 = input("Enter text 1: ")
text2 = input("Enter text 2: ")
#Convert text to embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
#Calculate similarity
similarity = util.cos_sim(embedding1, embedding2)
#Shoe result
print("\nSimilarity Score:",round(float(similarity), 2))
if similarity > 0.75:
  print("Similarity Level: High")
elif similarity > 0.4:
  print("Similarity Level: Medium")
else:
  print("Similarity Level: Low")

