# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lAxGOD56iBYsTwj5MSiXL64bZgwWrvBD
"""

from transformers import pipeline
generator=pipeline("sentiment-analysis")
result=generator("I love learning AI!")
print(result)

!pip install matplotlib

import matplotlib.pyplot as plt

import matplotlib.pyplot as plt
x=[1,2,3,4]
y=[10,20,25,30]
plt.plot(x,y)
plt.title("simple line graph")
plt.xlabel("X Axis")
plt.ylabel("y Axis")
plt.show()

import matplotlib.pyplot as plt
students=["john","Anna","Mike","sara"]
marks=[85,90,78,92]
plt.bar(students,marks)
plt.xlabel("students")
plt.ylabel("marks")
plt.show()