# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPPDqhRUQJ8kAnxoEHGz5LDKSs6F4BZh
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd