# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpZV2sEzSYU3fXiX8Ws7pDNMTR56v4vA
"""

def demo():
 nums = [1,2,3,4,5]
 # list comprehension: squares
 squares = [x*x for x in nums]
 # dict comprehension: number -> square
 square_dict = {x: x*x for x in nums}
 # set comprehension: distinct remainders mod 3
 remainders = {x % 3 for x in nums}
 # generator comprehension (lazy)
 gen = (x*x for x in nums)
 print("squares:", squares)
 print("square_dict:", square_dict)
 print("remainders:", remainders)
 print("generator values:", [next(gen) for _ in range(len(nums))])
if __name__ == "__main__":
 demo()