# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REO9y8Qy6GzzHjmXfFqUOFSCWVpShEm_
"""

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

# User Inputs
subjects_input = input("Enter subjects (comma separated): ")
days_input = input("Enter days (comma separated): ")
periods_per_day = int(input("Enter number of periods per day: "))

# Process Inputs
subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]

# Validation
if not subjects or not days or periods_per_day <= 0:
    print("Invalid input. Please provide valid subjects, days, and a positive number of periods per day.")
else:
    timetable = {}
    for day in days:
        timetable[day] = random.choices(subjects, k=periods_per_day)

    # Create DataFrame
    df = pd.DataFrame(timetable)
    df.index = [f"Period {i+1}" for i in range(periods_per_day)]

    print("\nTimetable Generated Successfully\n")
    display(df)

    # Save timetable
    df.to_csv("timetable.csv")
    print("\nTimetable saved as timetable.csv")

# Meeting Minutes Generator
#
import pandas as pd
from datetime import datetime
print("MEETING MINUTES GENERATOR\n")
# User Inputs
meeting_title = input("Enter meeting title: ")
meeting_date = input("Enter meeting date (DD-MM-YYYY): ")
meeting_time = input("Enter meeting time: ")
participants = input("Enter participants (comma separated): ")
agenda = input("Enter agenda points (comma separated): ")
decisions = input("Enter decisions taken (comma separated): ")
action_items = input("Enter action items (comma separated): ")
prepared_by = input("Prepared by: ")

# Process Inputs
participants_list = [p.strip() for p in participants.split(",") if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",") if a.strip()]
decisions_list = [d.strip() for d in decisions.split(",") if d.strip()]
actions_list = [a.strip() for a in action_items.split(",") if a.strip()]

# Create structured meeting minutes

# Create structured meeting minutes
minutes = {
    "Meeting Title": meeting_title,
    "Date": meeting_date,
    "Time": meeting_time,
    "Participants": ", ".join(participants_list),
    "Agenda": "; ".join(agenda_list),
    "Decisions Taken": "; ".join(decisions_list),
    "Action Items": "; ".join(actions_list),
    "Prepared By": prepared_by,
    "Generated On": datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}

# Convert to DataFrame
df = pd.DataFrame(list(minutes.items()), columns=["Field", "Details"])
print("\nMeeting Minutes Generated Successfully\n")
display(df)

# Save as CSV
df.to_csv("meeting_minutes.csv", index=False)
print("\nFile saved as meeting_minutes.csv")